/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 178a34f827dd99b076826e6f66cba361)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		CUSTOM_DOMAIN: string;
		ENVIRONMENT: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		JWT_SECRET: string;
		WEBHOOK_SECRET: string;
		ACI_API_URL: string;
		ACI_API_KEY: string;
		ANTHROPIC_API_KEY?: string;
		OPENAI_API_KEY?: string;
		OPENROUTER_API_KEY?: string;
		GROQ_API_KEY?: string;
		SECRETS_ENCRYPTION_KEY?: string;
		CF_ACCESS_ID?: string;
		CF_ACCESS_SECRET?: string;
		SENTRY_DSN?: string;
		CLOUDFLARE_AI_GATEWAY_URL?: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN?: string;
		GITHUB_EXPORTER_CLIENT_ID?: string;
		GITHUB_EXPORTER_CLIENT_SECRET?: string;
		GITHUB_CLIENT_ID?: string;
		GITHUB_CLIENT_SECRET?: string;
		GOOGLE_CLIENT_ID?: string;
		GOOGLE_CLIENT_SECRET?: string;
		SANDBOX_SERVICE_TYPE?: string;
		SANDBOX_SERVICE_URL?: string;
		SANDBOX_SERVICE_API_KEY?: string;
		ALLOCATION_STRATEGY?: string;
		USE_TUNNEL_FOR_PREVIEW?: string;
		CUSTOM_PREVIEW_DOMAIN?: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		IMAGES: ImagesBinding;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "CUSTOM_DOMAIN" | "ENVIRONMENT" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN" | "GOOGLE_AI_STUDIO_API_KEY" | "JWT_SECRET" | "WEBHOOK_SECRET" | "ACI_API_URL" | "ACI_API_KEY">> {}
}
