import { build } from "esbuild"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const src = (...p) => resolve(__dirname, "src", ...p)

// Alias map — resolves @/ imports from upstream-ported modules to our shim files.
// Mirrors the [alias] section that was in wrangler.toml.
const aliasMap = {
  "@/agent/agent": src("agent/agent.ts"),
  "@/auth": src("auth/index.ts"),
  "@/bus": src("bus.ts"),
  "@/bus/bus-event": src("bus/bus-event.ts"),
  "@/bus/global": src("bus/global.ts"),
  "@/config/config": src("config/config.ts"),
  "@/config/markdown": src("config/markdown.ts"),
  "@/command": src("command/index.ts"),
  "@/effect/cross-spawn-spawner": src("effect/cross-spawn-spawner.ts"),
  "@/effect/instance-state": src("effect/instance-state.ts"),
  "@/effect/run-service": src("effect/run-service.ts"),
  "@/effect/runner": src("effect/runner.ts"),
  "@/file/ripgrep": src("file/ripgrep.ts"),
  "@/file/time": src("file/time.ts"),
  "@/filesystem": src("filesystem/index.ts"),
  "@/flag/flag": src("flag/flag.ts"),
  "@/global": src("global/index.ts"),
  "@/id/id": src("id/id.ts"),
  "@/installation": src("installation/index.ts"),
  "@/lsp": src("lsp/index.ts"),
  "@/mcp": src("mcp/index.ts"),
  "@/permission": src("permission/index.ts"),
  "@/plugin": src("plugin/index.ts"),
  "@/project/instance": src("project/instance.ts"),
  "@/project/schema": src("project/schema.ts"),
  "@/provider/error": src("provider/error.ts"),
  "@/provider/provider": src("provider/provider.ts"),
  "@/provider/schema": src("provider/schema.ts"),
  "@/provider/transform": src("provider/transform.ts"),
  "@/question": src("question/index.ts"),
  "@/shell/shell": src("shell/shell.ts"),
  "@/skill": src("skill/index.ts"),
  "@/snapshot": src("snapshot/index.ts"),
  "@/storage/db": src("storage/db.ts"),
  "@/storage/storage": src("storage/storage.ts"),
  "@/sync": src("sync/index.ts"),
  "@/tool/read": src("tool/read.ts"),
  "@/tool/registry": src("tool/registry.ts"),
  "@/tool/task": src("tool/task.ts"),
  "@/tool/tool": src("tool/tool.ts"),
  "@/tool/truncate": src("tool/truncate.ts"),
  "@/util/data-url": src("util/data-url.ts"),
  "@/util/effect-http-client": src("util/effect-http-client.ts"),
  "@/util/error": src("util/error.ts"),
  "@/util/fn": src("util/fn.ts"),
  "@/util/iife": src("util/iife.ts"),
  "@/util/lazy": src("util/lazy.ts"),
  "@/util/log": src("util/log.ts"),
  "@/util/process": src("util/process.ts"),
  "@/util/record": src("util/record.ts"),
  "@/util/schema": src("util/schema.ts"),
  "@/util/token": src("util/token.ts"),
  "@/util/update-schema": src("util/update-schema.ts"),
  "@/session/prompt": src("prompt/index.ts"),
  "@opencode-ai/util/error": src("vendor/named-error.ts"),
  "@opencode-ai/util/slug": src("vendor/slug.ts"),
  "gitlab-ai-provider": src("vendor/gitlab-ai-provider.ts"),
}

// External packages — not bundled into the library output.
// Consumers provide these via their own node_modules / wrangler bundling.
const external = [
  // Workers runtime
  "cloudflare:workers",
  // npm deps — consumer provides via their own node_modules
  "hono",
  "hono/*",
  "ai",
  "ai/*",
  "@ai-sdk/*",
  "@cloudflare/shell",
  "@cloudflare/shell/*",
  "@cloudflare/worker-bundler",
  "ai-gateway-provider",
  "ai-gateway-provider/*",
  "effect",
  "effect/*",
  "zod",
  "zod/*",
  "ulid",
  "remeda",
  "decimal.js",
  "qrcode-generator",
  "drizzle-orm",
  "drizzle-orm/*",
  // Node built-ins (Workers provides nodejs_compat)
  "node:*",
  "crypto",
  "path",
  "os",
  "url",
  "fs",
  "stream",
  "buffer",
  "util",
  "events",
  "assert",
  "http",
  "https",
  "net",
  "tls",
  "zlib",
  "querystring",
  // isomorphic-git transitive deps (pulled in by @cloudflare/shell)
  "isomorphic-git",
  "isomorphic-git/*",
  "crc-32",
  "clean-git-ref",
  "diff3",
  "inherits",
  "sha.js",
  "sha.js/*",
]

await build({
  entryPoints: [src("index.ts")],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  mainFields: ["module", "main"],
  outdir: resolve(__dirname, "dist"),
  alias: aliasMap,
  external,
  sourcemap: true,
  // Text loader for .md and .txt files (prompt templates, etc.)
  loader: {
    ".md": "text",
    ".txt": "text",
  },
  logLevel: "info",
})

console.log("✓ Build complete → dist/")
