/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c4ca3291a228d4eb5c75eb914432a30a)
interface __BaseEnv_Env {
  ARTIFACTS_ACCOUNT_ID: string;
  ARTIFACTS_NAMESPACE: string;
  ARTIFACTS_API_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ARTIFACTS_ACCOUNT_ID" | "ARTIFACTS_NAMESPACE" | "ARTIFACTS_API_TOKEN">
  > {}
}
