// AUTO-GENERATED by scripts/gen-skill-manifest.mjs — do not edit
import SKILL_0 from "../../skills/cloudflare-bundler-apps/SKILL.md"
import SKILL_1 from "../../skills/frontend-design/SKILL.md"
import SKILL_2 from "../../skills/frontend-design-cloudflare-theme/SKILL.md"

export const skills = [
  { dir: "cloudflare-bundler-apps", raw: SKILL_0 },
  { dir: "frontend-design", raw: SKILL_1 },
  { dir: "frontend-design-cloudflare-theme", raw: SKILL_2 },
]
